export const SET_SITE_CONFIG = 'SET_SITE_CONFIG';
export const SET_SITE_CONFIG_ERROR = 'SET_SITE_CONFIG_ERROR';
export const SAVING_SITE_CONFIG = 'SAVING_SITE_CONFIG';
export const SAVING_SITE_CONFIG_ERROR = 'SAVING_SITE_CONFIG_ERROR';

export const SET_TRANSLATIONS = 'SET_TRANSLATIONS';
export const SET_TRANSLATION = 'SET_TRANSLATION';
export const SET_TRANSLATIONS_ERROR = 'SET_TRANSLATIONS_ERROR';
export const SAVING_TRANSLATIONS = 'SAVING_TRANSLATIONS_CONFIG';
export const SAVING_TRANSLATIONS_ERROR = 'SAVING_TRANSLATIONS_CONFIG_ERROR';
export const ADD_NEW_LANG = 'ADD_NEW_LANG';
export const REMOVE_LANG = 'REMOVE_LANG';

export const SET_REDIRECTS = 'SET_REDIRECTS';
export const SET_REDIRECTS_ERROR = 'SET_REDIRECTS_ERROR';
export const SAVING_REDIRECTS = 'SAVING_REDIRECTS';
export const SAVING_REDIRECTS_ERROR = 'SAVING_REDIRECTS_ERROR';

export const SET_CUSTOM_CODE = 'SET_CUSTOM_CODE';
export const SET_CUSTOM_CODE_ERROR = 'SET_CUSTOM_CODE_ERROR';
export const SAVING_CUSTOM_CODE = 'SAVING_CUSTOM_CODE';
export const SAVING_CUSTOM_CODE_ERROR = 'SAVING_CUSTOM_CODE_ERROR';


export const FETCHING_ALL = 'FETCHING_ALL';
export const FETCHING_ALL_ERROR = 'FETCHING_ALL_ERROR';
export const FETCHING_ALL_SUCCESS = 'FETCHING_ALL_SUCCESS';