export const SET_SITE_CONFIG = 'SET_SITE_CONFIG';
export const SET_SITE_CONFIG_ERROR = 'SET_SITE_CONFIG_ERROR';
export const SAVING_SITE_CONFIG = 'SAVING_SITE_CONFIG';
export const SAVING_SITE_CONFIG_ERROR = 'SAVING_SITE_CONFIG_ERROR';

export const SET_TRANSLATIONS = 'SET_TRANSLATIONS';
export const SET_TRANSLATION = 'SET_TRANSLATION';
export const SET_TRANSLATIONS_ERROR = 'SET_TRANSLATIONS_ERROR';
export const SAVING_TRANSLATIONS = 'SAVING_TRANSLATIONS_CONFIG';
export const SAVING_TRANSLATIONS_ERROR = 'SAVING_TRANSLATIONS_CONFIG_ERROR';
export const ADD_NEW_LANG = 'ADD_NEW_LANG';
export const REMOVE_LANG = 'REMOVE_LANG';
