export const SET_SITE_CONFIG = 'SET_SITE_CONFIG';
export const SET_SITE_CONFIG_ERROR = 'SET_SITE_CONFIG_ERROR';
export const SAVING_SITE_CONFIG = 'SAVING_SITE_CONFIG';
export const SAVING_SITE_CONFIG_ERROR = 'SAVING_SITE_CONFIG_ERROR';
