<?php

namespace Rentivo_Simba\Admin;

// Abort if this file is called directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! class_exists( CustomLazyBlocks::class ) ) {
	class CustomLazyBlocks {
	    /*
	    public function __construct() {
            add_action( 'plugins_loaded', array($this, 'register_lazy_blocks'), 1 );
        }*/


        public function theme_lzb_url( $url ) {
            return THEME_LZB_URL;
        }

        /**
         * Register blocks
         */
        public function register_lazy_blocks() {
            if ( function_exists( 'lazyblocks' ) ) :

                lazyblocks()->add_block( array(
                    'id' => 365,
                    'title' => 'Enquiry Form',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/enquiry-form',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_2839c946bf' => array(
                            'type' => 'select',
                            'name' => 'enquiryType',
                            'default' => 'customer',
                            'label' => 'Enquiry Type',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Customer Enquiry',
                                    'value' => 'customer',
                                ),
                                array(
                                    'label' => 'Business Enquiry',
                                    'value' => 'business',
                                ),
                            ),
                        ),
                        'control_2eda074f7f' => array(
                            'type' => 'select',
                            'name' => 'buttonType',
                            'default' => 'primary',
                            'label' => 'Button Type',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Primary',
                                    'value' => 'primary',
                                ),
                                array(
                                    'label' => 'Secondary',
                                    'value' => 'secondary',
                                ),
                                array(
                                    'label' => 'Default',
                                    'value' => 'default',
                                ),
                            ),
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 255,
                    'title' => 'Inner Row Block',
                    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/inner-row-block',
                    'description' => '',
                    'category' => 'lazyblocks',
                    'category_label' => 'lazyblocks',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => true,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_26e9e941d5' => array(
                            'type' => 'inner_blocks',
                            'name' => 'content',
                            'default' => '',
                            'label' => '',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 217,
                    'title' => 'Theme Buttons',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M6 6h12v12H6z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/theme-buttons',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_59ea434379' => array(
                            'type' => 'repeater',
                            'name' => 'buttons',
                            'default' => '',
                            'label' => 'Buttons',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'rows_label' => 'Button',
                            'rows_add_button_label' => '+ Add Button',
                            'rows_min' => '1',
                            'rows_max' => '4',
                            'rows_collapsible' => 'false',
                        ),
                        'control_c8d9c64d59' => array(
                            'type' => 'select',
                            'name' => 'type',
                            'default' => 'primary',
                            'label' => 'Type',
                            'help' => '',
                            'child_of' => 'control_59ea434379',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Primary',
                                    'value' => 'primary',
                                ),
                                array(
                                    'label' => 'Default',
                                    'value' => 'default',
                                ),
                                array(
                                    'label' => 'Secondary',
                                    'value' => 'secondary',
                                ),
                                array(
                                    'label' => 'White',
                                    'value' => 'white',
                                ),
                            ),
                        ),
                        'control_ce4870492e' => array(
                            'type' => 'toggle',
                            'name' => 'ghost',
                            'default' => '',
                            'label' => 'Ghost (Outlined Only)',
                            'help' => '',
                            'child_of' => 'control_59ea434379',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_c979cc459f' => array(
                            'type' => 'toggle',
                            'name' => 'block',
                            'default' => '',
                            'label' => 'Block (Full Width)',
                            'help' => '',
                            'child_of' => 'control_59ea434379',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_5b78b848b0' => array(
                            'type' => 'select',
                            'name' => 'size',
                            'default' => 'default',
                            'label' => 'Size',
                            'help' => '',
                            'child_of' => 'control_59ea434379',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Medium (Default)',
                                    'value' => 'default',
                                ),
                                array(
                                    'label' => 'Small',
                                    'value' => 'small',
                                ),
                                array(
                                    'label' => 'Large',
                                    'value' => 'large',
                                ),
                            ),
                        ),
                        'control_de196248ba' => array(
                            'type' => 'text',
                            'name' => 'label',
                            'default' => 'Click me!',
                            'label' => 'Label',
                            'help' => '',
                            'child_of' => 'control_59ea434379',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_322ba34ecf' => array(
                            'type' => 'text',
                            'name' => 'link',
                            'default' => '',
                            'label' => 'Link',
                            'help' => '',
                            'child_of' => 'control_59ea434379',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_ccc9ea4e87' => array(
                            'type' => 'select',
                            'name' => 'alignButtons',
                            'default' => 'left',
                            'label' => 'Align',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Left',
                                    'value' => 'left',
                                ),
                                array(
                                    'label' => 'Right',
                                    'value' => 'right',
                                ),
                                array(
                                    'label' => 'Center',
                                    'value' => 'center',
                                ),
                            ),
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '<style>
        .wgp-button {
            display: inline-block;
            outline:0;
            border:0;
            background-color: #333;
            color:white;
            padding:10px 15px;
        }
    </style>
    {{#each buttons}}
            <button class="wgp-button">{{this.label}}</button>
    {{/each}}
    ',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 15,
                    'title' => 'Section Title',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M5 17v2h14v-2H5zm4.5-4.2h5l.9 2.2h2.1L12.75 4h-1.5L6.5 15h2.1l.9-2.2zM12 5.98L13.87 11h-3.74L12 5.98z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/section-title',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_0318564885' => array(
                            'type' => 'textarea',
                            'name' => 'title',
                            'default' => '',
                            'label' => 'Title',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'true',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_6fcb2c4640' => array(
                            'type' => 'textarea',
                            'name' => 'subtitle',
                            'default' => '',
                            'label' => 'Subtitle',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_6e59bb4ac3' => array(
                            'type' => 'select',
                            'name' => 'textAlign',
                            'default' => 'center',
                            'label' => 'Text Align',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Center',
                                    'value' => 'center',
                                ),
                                array(
                                    'label' => 'Left',
                                    'value' => 'left',
                                ),
                                array(
                                    'label' => 'Right',
                                    'value' => 'right',
                                ),
                            ),
                        ),
                        'control_9d38be4dc8' => array(
                            'type' => 'range',
                            'name' => 'level',
                            'default' => '2',
                            'label' => 'Level',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'min' => '2',
                            'max' => '5',
                            'step' => '1',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '<div style="text-align:{{textAlign}};">
        {{#if title}}<h2 style="margin-bottom:5px; margin-top:0;">{{title}}</h2>{{/if}}
        {{#if subtitle}}<p style="margin:0;">{{subtitle}}</p>{{/if}}
    </div>',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 14,
                    'title' => 'Featurette',
                    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/featurette',
                    'description' => '',
                    'category' => 'lazyblocks',
                    'category_label' => 'lazyblocks',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_50b98640f9' => array(
                            'type' => 'text',
                            'name' => 'title',
                            'default' => '',
                            'label' => 'Title',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_5639f74e33' => array(
                            'type' => 'text',
                            'name' => 'subtitle',
                            'default' => '',
                            'label' => 'Subtitle',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_e3298e4ec8' => array(
                            'type' => 'image',
                            'name' => 'icon',
                            'default' => '',
                            'label' => 'Icon',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '<div style="text-align:center;">
        {{#if icon.url}}<img src="{{icon.url}}" width="25%" style="margin-bottom:5px;"/>{{/if}}
        {{#if title}}<h4 style="margin:0;">{{title}}</h4>{{/if}}
        {{#if subtitle}}<p style="margin:0;">{{subtitle}}</p>{{/if}}
    </div>',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 13,
                    'title' => 'Row Block',
                    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/row-block',
                    'description' => '',
                    'category' => 'lazyblocks',
                    'category_label' => 'lazyblocks',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => true,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_26e9e941d5' => array(
                            'type' => 'inner_blocks',
                            'name' => 'content',
                            'default' => '',
                            'label' => '',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_fd18b447c0' => array(
                            'type' => 'color',
                            'name' => 'bgColor',
                            'default' => '#ffffff',
                            'label' => 'Background Color',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_b77b924589' => array(
                            'type' => 'toggle',
                            'name' => 'useThemeHighlight',
                            'default' => '',
                            'label' => 'Theme Highlight',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'false',
                        ),
                        'control_dffa0a4df3' => array(
                            'type' => 'checkbox',
                            'name' => 'useLightText',
                            'default' => '',
                            'label' => 'Use Light Text',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_2cba9141e9' => array(
                            'type' => 'select',
                            'name' => 'rowType',
                            'default' => 'default',
                            'label' => 'Row Type',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Default',
                                    'value' => 'default',
                                ),
                                array(
                                    'label' => 'Large Padding',
                                    'value' => 'largePadding',
                                ),
                                array(
                                    'label' => 'Screen Height',
                                    'value' => 'screenHeight',
                                ),
                            ),
                        ),
                        'control_763bdd4c3e' => array(
                            'type' => 'toggle',
                            'name' => 'flush',
                            'default' => '',
                            'label' => 'Flush',
                            'help' => 'Only applies if aligned full width',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_841ab44148' => array(
                            'type' => 'toggle',
                            'name' => 'smallerFontSize',
                            'default' => '',
                            'label' => 'Smaller Font Size',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 12,
                    'title' => 'Card',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21 19V5c0-1.1-.9-2-2-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2zM8.5 13.5l2.5 3.01L14.5 12l4.5 6H5l3.5-4.5z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/card',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'full',
                            1 => 'wide',
                            2 => 'left',
                            3 => 'center',
                            4 => 'right',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_7f28bc44b2' => array(
                            'type' => 'image',
                            'name' => 'image',
                            'default' => '',
                            'label' => 'Image',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_b87a3843b1' => array(
                            'type' => 'text',
                            'name' => 'title',
                            'default' => '',
                            'label' => 'Title',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_559be04d66' => array(
                            'type' => 'text',
                            'name' => 'subtitle',
                            'default' => '',
                            'label' => 'Subtitle',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_c0b8a44cec' => array(
                            'type' => 'text',
                            'name' => 'link',
                            'default' => '',
                            'label' => 'Link',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_411b77403e' => array(
                            'type' => 'toggle',
                            'name' => 'overlayImage',
                            'default' => '',
                            'label' => 'Overlay Image',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_20985a4721' => array(
                            'type' => 'color',
                            'name' => 'bgOverlayColor',
                            'default' => 'rgba(0,0,0,0.2)',
                            'label' => 'Background Overlay Color',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'alpha' => 'true',
                        ),
                        'control_aee981448e' => array(
                            'type' => 'select',
                            'name' => 'aspect',
                            'default' => '1/1',
                            'label' => 'Aspect Ratio',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => '1/1',
                                    'value' => '1/1',
                                ),
                                array(
                                    'label' => '4/3',
                                    'value' => '4/3',
                                ),
                                array(
                                    'label' => '3/4',
                                    'value' => '3/4',
                                ),
                                array(
                                    'label' => '16/9',
                                    'value' => '16/9',
                                ),
                            ),
                        ),
                        'control_200af6490b' => array(
                            'type' => 'text',
                            'name' => 'ribbonText',
                            'default' => '',
                            'label' => 'Ribbon Text',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '<div>
        {{#if image.url}}<div style="padding-bottom:100%; height:0; background-image:url({{image.url}}); background-size:cover;"></div>{{/if}}
        {{#if title}}<h4 style="margin:0;">{{title}}</h4>{{/if}}
        {{#if subtitle}}<p style="margin:0;">{{subtitle}}</p>{{/if}}
    </div>',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 11,
                    'title' => 'Search Bar',
                    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/search-bar',
                    'description' => '',
                    'category' => 'lazyblocks',
                    'category_label' => 'lazyblocks',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'left',
                            1 => 'right',
                            2 => 'center',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_553bf0472e' => array(
                            'type' => 'toggle',
                            'name' => 'stacked',
                            'default' => '',
                            'label' => 'Stacked',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '<div style="color:black; text-align:center; font-weight:bold;">Search Bar</div>',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 10,
                    'title' => 'Hero Gallery',
                    'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <rect opacity="0.25" width="15" height="15" rx="4" transform="matrix(-1 0 0 1 22 7)" fill="currentColor" />
    <rect width="15" height="15" rx="4" transform="matrix(-1 0 0 1 17 2)" fill="currentColor" />
    </svg>
    ',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/hero-gallery',
                    'description' => '',
                    'category' => 'lazyblocks',
                    'category_label' => 'lazyblocks',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => false,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_a5dacf43f3' => array(
                            'type' => 'gallery',
                            'name' => 'images',
                            'default' => '',
                            'label' => 'Images',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_75da7a4e4b' => array(
                            'type' => 'number',
                            'name' => 'height',
                            'default' => '450',
                            'label' => 'Height (px)',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'step' => '1',
                        ),
                        'control_1a9a8645c7' => array(
                            'type' => 'toggle',
                            'name' => 'fullHeight',
                            'default' => '',
                            'label' => 'Full Height',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_1e0bf44568' => array(
                            'type' => 'toggle',
                            'name' => 'bgOverlay',
                            'default' => '',
                            'label' => 'Background Overlay',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_0bf85b467e' => array(
                            'type' => 'color',
                            'name' => 'bgOverlayColor',
                            'default' => 'rgba(0,0,0,0.1)',
                            'label' => 'Background Overlay Color',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'alpha' => 'true',
                        ),
                        'control_9fab5d485a' => array(
                            'type' => 'inner_blocks',
                            'name' => 'content',
                            'default' => '',
                            'label' => '',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_f83b81439f' => array(
                            'type' => 'toggle',
                            'name' => 'dots',
                            'default' => '',
                            'label' => 'Show Dots',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_3bbbd4403a' => array(
                            'type' => 'toggle',
                            'name' => 'arrows',
                            'default' => '',
                            'label' => 'Show Arrows',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_b6b8054208' => array(
                            'type' => 'number',
                            'name' => 'speed',
                            'default' => '500',
                            'label' => 'Slide Speed (ms)',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'step' => '100',
                            'min' => '100',
                            'max' => '2000',
                        ),
                        'control_952a8d41c3' => array(
                            'type' => 'toggle',
                            'name' => 'autoplay',
                            'default' => '',
                            'label' => 'Auto Play',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_6abb7e4ab4' => array(
                            'type' => 'number',
                            'name' => 'autoplaySpeed',
                            'default' => '3000',
                            'label' => 'Auto Play Speed (ms)',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'step' => '1',
                            'min' => '1000',
                            'max' => '30000',
                        ),
                        'control_4759434785' => array(
                            'type' => 'toggle',
                            'name' => 'draggable',
                            'default' => '',
                            'label' => 'Draggable',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_518a6d48b6' => array(
                            'type' => 'toggle',
                            'name' => 'infinite',
                            'default' => '',
                            'label' => 'Infinite',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_5bc906448e' => array(
                            'type' => 'toggle',
                            'name' => 'fade',
                            'default' => '',
                            'label' => 'Fade',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_1cead4461f' => array(
                            'type' => 'toggle',
                            'name' => 'lazyLoad',
                            'default' => '',
                            'label' => 'Lazy Load',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_b6683a40f4' => array(
                            'type' => 'number',
                            'name' => 'slidesToShow',
                            'default' => '1',
                            'label' => 'Slides To Show',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'min' => '1',
                            'max' => '3',
                            'step' => '1',
                        ),
                        'control_5e4a0544d2' => array(
                            'type' => 'number',
                            'name' => 'slidesToScroll',
                            'default' => '1',
                            'label' => 'Slides To Scroll',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'min' => '1',
                            'max' => '3',
                            'step' => '0',
                        ),
                        'control_6418ae41bf' => array(
                            'type' => 'number',
                            'name' => 'spacing',
                            'default' => '0',
                            'label' => 'Spacing',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'min' => '0',
                            'max' => '500',
                            'step' => '1',
                        ),
                        'control_a26b454527' => array(
                            'type' => 'toggle',
                            'name' => 'splitScreen',
                            'default' => '',
                            'label' => 'Split Screen',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_d3b94e4087' => array(
                            'type' => 'select',
                            'name' => 'splitAlignImage',
                            'default' => 'right',
                            'label' => 'Split Align Image',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Right',
                                    'value' => 'right',
                                ),
                                array(
                                    'label' => 'Left',
                                    'value' => 'left',
                                ),
                            ),
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 9,
                    'title' => 'Featured Properties',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/featured-properties',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_7608a34214' => array(
                            'type' => 'select',
                            'name' => 'displayType',
                            'default' => 'carousel',
                            'label' => 'Type',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Carousel',
                                    'value' => 'carousel',
                                ),
                            ),
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 8,
                    'title' => 'Newsletter',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/newsletter',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_1e994a45ee' => array(
                            'type' => 'select',
                            'name' => 'provider',
                            'default' => 'mailchimp',
                            'label' => 'Provider',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Mailchimp',
                                    'value' => 'mailchimp',
                                ),
                            ),
                        ),
                        'control_554bff416b' => array(
                            'type' => 'text',
                            'name' => 'formAction',
                            'default' => '',
                            'label' => 'Form Action',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'true',
                            'placeholder' => 'https://youraccount.us11.list-manage.com/subscribe/post?u=54321&id=12345',
                            'characters_limit' => '',
                        ),
                        'control_5928714099' => array(
                            'type' => 'checkbox',
                            'name' => 'requireFirstName',
                            'default' => '',
                            'label' => 'Require First Name',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'checked' => 'true',
                        ),
                        'control_4e2917487c' => array(
                            'type' => 'select',
                            'name' => 'buttonType',
                            'default' => 'primary',
                            'label' => 'Button Type',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Primary',
                                    'value' => 'primary',
                                ),
                                array(
                                    'label' => 'Secondary',
                                    'value' => 'secondary',
                                ),
                                array(
                                    'label' => 'Default',
                                    'value' => 'default',
                                ),
                                array(
                                    'label' => 'Ghost Primary',
                                    'value' => 'ghostPrimary',
                                ),
                                array(
                                    'label' => 'Ghost Secondary',
                                    'value' => 'ghostSecondary',
                                ),
                                array(
                                    'label' => 'Ghost Default',
                                    'value' => 'ghostDefault',
                                ),
                            ),
                        ),
                        'control_0c5bbc4ff0' => array(
                            'type' => 'select',
                            'name' => 'newsletterAlign',
                            'default' => 'center',
                            'label' => 'Align',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Center',
                                    'value' => 'center',
                                ),
                                array(
                                    'label' => 'Left',
                                    'value' => 'left',
                                ),
                                array(
                                    'label' => 'Right',
                                    'value' => 'right',
                                ),
                            ),
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

                lazyblocks()->add_block( array(
                    'id' => 7,
                    'title' => 'Menu',
                    'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M4 14h4v-4H4v4zm0 5h4v-4H4v4zM4 9h4V5H4v4zm5 5h12v-4H9v4zm0 5h12v-4H9v4zM9 5v4h12V5H9z" /></svg>',
                    'keywords' => array(
                    ),
                    'slug' => 'lazyblock/menu',
                    'description' => '',
                    'category' => 'common',
                    'category_label' => 'common',
                    'supports' => array(
                        'customClassName' => true,
                        'anchor' => false,
                        'align' => array(
                            0 => 'wide',
                            1 => 'full',
                        ),
                        'html' => false,
                        'multiple' => true,
                        'inserter' => true,
                    ),
                    'ghostkit' => array(
                        'supports' => array(
                            'spacings' => false,
                            'display' => false,
                            'scrollReveal' => false,
                        ),
                    ),
                    'controls' => array(
                        'control_9b6a1d422c' => array(
                            'type' => 'repeater',
                            'name' => 'items',
                            'default' => '',
                            'label' => 'Items',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'rows_label' => 'item',
                            'rows_add_button_label' => '+ Add Item',
                            'rows_min' => '1',
                            'rows_max' => '50',
                            'rows_collapsed' => 'false',
                        ),
                        'control_96e8774337' => array(
                            'type' => 'text',
                            'name' => 'label',
                            'default' => '',
                            'label' => 'Label',
                            'help' => '',
                            'child_of' => 'control_9b6a1d422c',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'true',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_edb8a94e34' => array(
                            'type' => 'text',
                            'name' => 'url',
                            'default' => '',
                            'label' => 'URL',
                            'help' => '',
                            'child_of' => 'control_9b6a1d422c',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_5d0b834b3f' => array(
                            'type' => 'select',
                            'name' => 'menuType',
                            'default' => 'vertical',
                            'label' => 'Type',
                            'help' => '',
                            'child_of' => '',
                            'placement' => 'inspector',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'true',
                            'placeholder' => '',
                            'characters_limit' => '',
                            'choices' => array(
                                array(
                                    'label' => 'Vertical',
                                    'value' => 'vertical',
                                ),
                                array(
                                    'label' => 'Horizontal',
                                    'value' => 'horizontal',
                                ),
                            ),
                        ),
                        'control_765b84418f' => array(
                            'type' => 'toggle',
                            'name' => 'newTab',
                            'default' => '',
                            'label' => 'Open In New Tab',
                            'help' => '',
                            'child_of' => 'control_9b6a1d422c',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                        'control_303bb741b1' => array(
                            'type' => 'toggle',
                            'name' => 'noFollow',
                            'default' => '',
                            'label' => 'No Follow',
                            'help' => '',
                            'child_of' => 'control_9b6a1d422c',
                            'placement' => 'content',
                            'width' => '100',
                            'hide_if_not_selected' => 'false',
                            'save_in_meta' => 'false',
                            'save_in_meta_name' => '',
                            'required' => 'false',
                            'placeholder' => '',
                            'characters_limit' => '',
                        ),
                    ),
                    'code' => array(
                        'editor_html' => '<ul>
        {{#each items}}
            <li>
                {{#if this.url}}
                    <a href="{{this.url}}">{{this.label}}</a>
                {{else}}
                    {{this.label}}
                {{/if}}
            {{/each}}
            </li>
    </ul>',
                        'editor_callback' => '',
                        'editor_css' => '',
                        'frontend_html' => '',
                        'frontend_callback' => '',
                        'frontend_css' => '',
                        'show_preview' => 'always',
                        'single_output' => false,
                        'use_php' => false,
                    ),
                    'condition' => array(
                    ),
                ) );

            endif;
        }
    }
}
